name: Build XMRig + Release

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [linux, windows, android]

    env:
      XMRIG_VERSION: 6.24.0

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Dependencies (Linux + Cross)
      run: |
        sudo apt update
        sudo apt install -y cmake build-essential git \
          libhwloc-dev libssl-dev libuv1-dev \
          mingw-w64 g++-mingw-w64 gcc-multilib g++-multilib \
          libc6-dev-i386 zip unzip

    - name: Install Android NDK
      if: matrix.target == 'android'
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27

    - name: Clone XMRig
      run: |
        git clone --recursive https://github.com/xmrig/xmrig.git

    - name: Clone and Patch libuv for Android
      if: matrix.target == 'android'
      run: |
        git clone https://github.com/libuv/libuv.git
        cd libuv
        sed -i '1i #undef HAVE_IFADDRS_H' src/unix/tcp.c

    - name: Build libuv (Android)
      if: matrix.target == 'android'
      run: |
        mkdir -p libuv/build && cd libuv/build
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-21 \
          -DCMAKE_BUILD_TYPE=Release
        cmake --build .

    - name: Build XMRig (Linux)
      if: matrix.target == 'linux'
      run: |
        mkdir -p xmrig/build && cd xmrig/build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build .
        strip xmrig
        zip -j ../../xmrig-linux.zip xmrig

    - name: Build XMRig (Windows)
      if: matrix.target == 'windows'
      run: |
        mkdir -p xmrig/build && cd xmrig/build
        cmake .. -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_SYSTEM_NAME=Windows \
          -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc \
          -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ \
          -DWITH_HWLOC=OFF
        cmake --build .
        zip -j ../../xmrig-windows.zip xmrig.exe

    - name: Build XMRig (Android)
      if: matrix.target == 'android'
      run: |
        mkdir -p xmrig/build && cd xmrig/build
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-21 \
          -DCMAKE_BUILD_TYPE=Release \
          -DLibUV_ROOT=../../libuv/build
        cmake --build .
        zip -j ../../xmrig-android.zip xmrig

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.XMRIG_VERSION }}
        files: |
          xmrig-linux.zip
          xmrig-windows.zip
          xmrig-android.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
